### ISSUE TITLE
No Deep Sleep and WOL

### ISSUE THREAD

**Issue by gorans** [SwimmingPig/Hackintosh-Intel-i5-10400-Gigabyte-Z490M-Gaming-X#1]
Hi,

I tried Your EFI and it's working OK (updated to OC 061). I just have two issues with sleep (power stays on) and Wake on Lan (doesn't work with WOL enabled in BIOS and in Energy Saver).

Is it working for You?

Best regards,
Goran

**Comment by SwimmingPig** [comment]
My system can sleep with no issue, it might be some controller that prevents your system to get into sleep mode. You can take a look at this blog and check your system. https://dortania.github.io/OpenCore-Post-Install/universal/sleep.html#preparations
And for the wake on LAN feature, I didn't use the feature so I can't give you a good answer.

**Comment by gorans** [comment]
Thanks for the reply.
My system sleeps also, but the power light stays on all the time. On my previous build, when system entered deep sleep, no lights were on, as if it's powered off, and I could wake it with kb/mouse or LAN.
Are the lights on Your rig on or off during sleep?

**Comment by SwimmingPig** [comment]
All the lights are off during sleep mode. Both the GPU logo light and the power button light is off when entered sleep. I will say if you have multiple light sources on your system, check if only the power light remains on and the others are off; Or all the lights remain on. For the first case, you might want to check the pins that connected the motherboard and the case. For the second case, it might be caused by opencore.
Also, if you have a clean install of windows on your machine, you can also sleep at windows and see the behavior to troubleshoot.

**Comment by gorans** [comment]
Thanks. No Windows but I will check other stuff.
Only pins connected are power button, power led and reset.
Thank You for Your time. 👍

**Comment by gorans** [comment]
OK. I reverted to Your original EFI and sleep is working as expected. I updated mine to 0.6.1 and probably made some mistake in the process.
You are still on 0.5.9?

**Comment by gorans** [comment]
I found the culprit. WOL is working with IntelMausiEthernet but not with IntelMausi. I'm now on working 0.6.2.
Just one more question: shouldn't we change BIOS to iMac20,1? Is there any benefit?

**Comment by SwimmingPig** [comment]
I'm still on version 0.5.9. Thanks for figuring that out! I'll push an EFI update when I upgrade to Big Sur.
And the version of the machine (iMac20, 1) doesn't matter a lot if the system is working. Different systems have different hardware requirements, and the best choice is the one that works without issue. So for me, I think if the hardware still supports the latest OS update, I will not hurry to change the system version.
